/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GO_AI;
import java.awt.Color;
public class Instructor_2 extends javax.swing.JFrame {

    /**
     * Creates new form Instructor_2
     */
    public Instructor_2() {
        initComponents();
        jLabel5.setText("HELLO, STUDENT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        workspace1 = new javax.swing.JPanel();
        wo1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        feedback = new javax.swing.JPanel();
        fe = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        robots = new javax.swing.JPanel();
        ro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        se = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        in1 = new javax.swing.JPanel();
        instructor1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(75, 155, 144));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("|");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-name-64.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(235, 235, 235));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 235, 235));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(35, 35, 35));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 230, 230));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 803, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(55, 55, 55));
        jPanel3.setLayout(null);

        workspace1.setBackground(new java.awt.Color(55, 55, 55));
        workspace1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workspace1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                workspace1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                workspace1MouseExited(evt);
            }
        });

        wo1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        wo1.setForeground(new java.awt.Color(235, 235, 235));
        wo1.setText("WORKSPACE");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-software-application-programming-with-brackets-and-slash-logotype-24.png"))); // NOI18N

        javax.swing.GroupLayout workspace1Layout = new javax.swing.GroupLayout(workspace1);
        workspace1.setLayout(workspace1Layout);
        workspace1Layout.setHorizontalGroup(
            workspace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workspace1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(21, 21, 21)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(wo1)
                .addGap(19, 19, 19))
        );
        workspace1Layout.setVerticalGroup(
            workspace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workspace1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workspace1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(workspace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wo1))
                .addContainerGap())
        );

        jPanel3.add(workspace1);
        workspace1.setBounds(0, 20, 180, 40);

        feedback.setBackground(new java.awt.Color(55, 55, 55));
        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feedbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feedbackMouseExited(evt);
            }
        });

        fe.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        fe.setForeground(new java.awt.Color(235, 235, 235));
        fe.setText("FEEDBACK");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-comments-25 (1).png"))); // NOI18N

        javax.swing.GroupLayout feedbackLayout = new javax.swing.GroupLayout(feedback);
        feedback.setLayout(feedbackLayout);
        feedbackLayout.setHorizontalGroup(
            feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(fe)
                .addGap(33, 33, 33))
        );
        feedbackLayout.setVerticalGroup(
            feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(fe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(feedback);
        feedback.setBounds(0, 80, 180, 47);

        robots.setBackground(new java.awt.Color(55, 55, 55));
        robots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robotsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                robotsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                robotsMouseExited(evt);
            }
        });

        ro.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        ro.setForeground(new java.awt.Color(235, 235, 235));
        ro.setText("ROBOTS");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-microprocessor-technology-with-artificial-intelligence-isolated-on-a-white-background-24.png"))); // NOI18N

        javax.swing.GroupLayout robotsLayout = new javax.swing.GroupLayout(robots);
        robots.setLayout(robotsLayout);
        robotsLayout.setHorizontalGroup(
            robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, robotsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(ro)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        robotsLayout.setVerticalGroup(
            robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(ro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(robots);
        robots.setBounds(0, 140, 180, 50);

        setting.setBackground(new java.awt.Color(55, 55, 55));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
        });

        se.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        se.setForeground(new java.awt.Color(235, 235, 235));
        se.setText("SETTING");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-advanced-search-24.png"))); // NOI18N

        javax.swing.GroupLayout settingLayout = new javax.swing.GroupLayout(setting);
        setting.setLayout(settingLayout);
        settingLayout.setHorizontalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(se)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        settingLayout.setVerticalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(se))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(setting);
        setting.setBounds(0, 200, 180, 46);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-go-back-64 (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 350, 60, 61);

        in1.setBackground(new java.awt.Color(75, 155, 144));
        in1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                in1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                in1MouseExited(evt);
            }
        });

        instructor1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        instructor1.setForeground(new java.awt.Color(235, 235, 235));
        instructor1.setText("INSTRUCTOR");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-instructor-teaching-about-its-geometrical-angle-isolated-on-a-white-background-24 (2).png"))); // NOI18N

        javax.swing.GroupLayout in1Layout = new javax.swing.GroupLayout(in1);
        in1.setLayout(in1Layout);
        in1Layout.setHorizontalGroup(
            in1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, in1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(instructor1)
                .addGap(19, 19, 19))
        );
        in1Layout.setVerticalGroup(
            in1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(in1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(in1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(instructor1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(55, 55, 55));
        jSeparator1.setForeground(new java.awt.Color(55, 55, 55));
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 55, 55), 1, true));

        t.setBackground(new java.awt.Color(55, 55, 55));
        t.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        t.setForeground(new java.awt.Color(204, 204, 204));
        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HASSAN TALAL", "HASSANTALAL@gmail.com", "01023435684", "CEO"},
                {"PISTA", "PISTA@gmail.com", "01552908587", "Computer Vision"},
                {"ABDULLAH", "ABDULLAH@gmail.com", "01094049867", "Electrical"},
                {"KASIM", "KASIM@gmail.com", "01030751725", "Embeded AI"},
                {"ADHAM", "ADHAM@gmail.com", "01157050658", "Graphic Designer"},
                {"KAREEM", "KAREEM@gmail.com", "01065390050", "Maintenance"},
                {"MOHAMED", "MOHAMED@gmail.com", "01001343385", "Robot Designer"},
                {"HEFNAWY", "HEFNAWY@gmail.com", "01006109957", "Coding"},
                {"SHEHAP", "SHEHAP@gmail.com", "01017300798", "3LA ALLAH"}
            },
            new String [] {
                "Instructor_Name", "Instructor_E-mail", "Instructor_Phone", "Instructor_Section"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t.setColumnSelectionAllowed(true);
        t.setRowHeight(48);
        t.setSelectionBackground(new java.awt.Color(75, 155, 144));
        t.setSelectionForeground(new java.awt.Color(55, 55, 55));
        t.getTableHeader().setResizingAllowed(false);
        t.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(t);
        t.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (t.getColumnModel().getColumnCount() > 0) {
            t.getColumnModel().getColumn(0).setResizable(false);
            t.getColumnModel().getColumn(1).setResizable(false);
            t.getColumnModel().getColumn(2).setResizable(false);
            t.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(in1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(new Color(55,55,55));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void workspace1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspace1MouseEntered
        workspace1.setBackground(new Color(20,20,20));
        wo1.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_workspace1MouseEntered

    private void workspace1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspace1MouseExited
        workspace1.setBackground(new Color(55,55,55));
        wo1.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_workspace1MouseExited

    private void feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseClicked
        new GO_AI.Feedback_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_feedbackMouseClicked

    private void feedbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseEntered
        feedback.setBackground(new Color(20,20,20));
        fe.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_feedbackMouseEntered

    private void feedbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseExited
        feedback.setBackground(new Color(55,55,55));
        fe.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_feedbackMouseExited

    private void robotsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotsMouseEntered
        robots.setBackground(new Color(20,20,20));
        ro.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_robotsMouseEntered

    private void robotsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotsMouseExited
        robots.setBackground(new Color(55,55,55));
        ro.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_robotsMouseExited

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        new GO_AI.Setting_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_settingMouseClicked

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered
        setting.setBackground(new Color(20,20,20));
        se.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited
        setting.setBackground(new Color(55,55,55));
        se.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_settingMouseExited

    private void in1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in1MouseEntered
       
    }//GEN-LAST:event_in1MouseEntered

    private void in1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in1MouseExited
       
    }//GEN-LAST:event_in1MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new GO_AI.Main_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void workspace1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspace1MouseClicked
        new GO_AI.Workspace_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_workspace1MouseClicked

    private void robotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotsMouseClicked
        new GO_AI.Robot_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_robotsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructor_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fe;
    private javax.swing.JPanel feedback;
    private javax.swing.JPanel in1;
    private javax.swing.JLabel instructor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel ro;
    private javax.swing.JPanel robots;
    private javax.swing.JLabel se;
    private javax.swing.JPanel setting;
    private javax.swing.JTable t;
    private javax.swing.JLabel wo1;
    private javax.swing.JPanel workspace1;
    // End of variables declaration//GEN-END:variables
}
