/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GO_AI;
import java.awt.Color;
public class Setting_2 extends javax.swing.JFrame {

    /**
     * Creates new form Setting_2
     */
    public Setting_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        redColor = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        Finish3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        in1 = new javax.swing.JPanel();
        instructor1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        workspace1 = new javax.swing.JPanel();
        wo1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        robots = new javax.swing.JPanel();
        ro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        feedback1 = new javax.swing.JPanel();
        fe1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Setting = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        se = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(75, 155, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(1088, 86));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("|");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-name-64.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(235, 235, 235));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 235, 235));
        jLabel5.setText("HELLO, STUDENT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(35, 35, 35));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 230, 230));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 803, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(55, 55, 55));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel4.setPreferredSize(new java.awt.Dimension(877, 456));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Ruby Radiance  :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Select your New Theme Style  :");

        redColor.setBackground(new java.awt.Color(55, 55, 55));
        redColor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        redColor.setForeground(new java.awt.Color(153, 153, 153));
        redColor.setText("RED EDITION");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-paint-brush-26.png"))); // NOI18N

        Finish3.setBackground(new java.awt.Color(75, 155, 144));
        Finish3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        Finish3.setForeground(new java.awt.Color(255, 255, 255));
        Finish3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Finish3.setText("DONE");
        Finish3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Finish3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Finish3MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-color-palette-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Finish3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel16)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)
                        .addGap(98, 98, 98)
                        .addComponent(redColor)
                        .addGap(0, 435, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(redColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(241, 241, 241)
                .addComponent(Finish3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));
        jPanel2.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-go-back-64 (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 100, 60, 61);

        jPanel3.setBackground(new java.awt.Color(55, 55, 55));
        jPanel3.setLayout(null);

        in1.setBackground(new java.awt.Color(55, 55, 55));
        in1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                in1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                in1MouseExited(evt);
            }
        });

        instructor1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        instructor1.setForeground(new java.awt.Color(235, 235, 235));
        instructor1.setText("INSTRUCTOR");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-instructor-teaching-about-its-geometrical-angle-isolated-on-a-white-background-24 (2).png"))); // NOI18N

        javax.swing.GroupLayout in1Layout = new javax.swing.GroupLayout(in1);
        in1.setLayout(in1Layout);
        in1Layout.setHorizontalGroup(
            in1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, in1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(instructor1)
                .addGap(19, 19, 19))
        );
        in1Layout.setVerticalGroup(
            in1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(in1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(in1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(instructor1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(in1);
        in1.setBounds(0, 30, 180, 40);

        workspace1.setBackground(new java.awt.Color(55, 55, 55));
        workspace1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workspace1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                workspace1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                workspace1MouseExited(evt);
            }
        });

        wo1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        wo1.setForeground(new java.awt.Color(235, 235, 235));
        wo1.setText("WORKSPACE");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-software-application-programming-with-brackets-and-slash-logotype-24.png"))); // NOI18N

        javax.swing.GroupLayout workspace1Layout = new javax.swing.GroupLayout(workspace1);
        workspace1.setLayout(workspace1Layout);
        workspace1Layout.setHorizontalGroup(
            workspace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workspace1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(21, 21, 21)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(wo1)
                .addGap(19, 19, 19))
        );
        workspace1Layout.setVerticalGroup(
            workspace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workspace1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workspace1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(workspace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wo1))
                .addContainerGap())
        );

        jPanel3.add(workspace1);
        workspace1.setBounds(0, 90, 180, 40);

        robots.setBackground(new java.awt.Color(55, 55, 55));
        robots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robotsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                robotsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                robotsMouseExited(evt);
            }
        });

        ro.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        ro.setForeground(new java.awt.Color(235, 235, 235));
        ro.setText("ROBOTS");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-microprocessor-technology-with-artificial-intelligence-isolated-on-a-white-background-24.png"))); // NOI18N

        javax.swing.GroupLayout robotsLayout = new javax.swing.GroupLayout(robots);
        robots.setLayout(robotsLayout);
        robotsLayout.setHorizontalGroup(
            robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, robotsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(ro)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        robotsLayout.setVerticalGroup(
            robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(ro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(robots);
        robots.setBounds(0, 190, 180, 50);

        feedback1.setBackground(new java.awt.Color(55, 55, 55));
        feedback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedback1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feedback1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feedback1MouseExited(evt);
            }
        });

        fe1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        fe1.setForeground(new java.awt.Color(235, 235, 235));
        fe1.setText("FEEDBACK");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-comments-25 (1).png"))); // NOI18N

        javax.swing.GroupLayout feedback1Layout = new javax.swing.GroupLayout(feedback1);
        feedback1.setLayout(feedback1Layout);
        feedback1Layout.setHorizontalGroup(
            feedback1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedback1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(fe1)
                .addGap(33, 33, 33))
        );
        feedback1Layout.setVerticalGroup(
            feedback1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedback1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedback1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(fe1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(feedback1);
        feedback1.setBounds(0, 140, 180, 50);

        jSeparator1.setBackground(new java.awt.Color(55, 55, 55));
        jSeparator1.setForeground(new java.awt.Color(55, 55, 55));

        Setting.setBackground(new java.awt.Color(75, 155, 144));
        Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GO_AI/icons8-advanced-search-24.png"))); // NOI18N

        se.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        se.setForeground(new java.awt.Color(235, 235, 235));
        se.setText("SETTING");

        javax.swing.GroupLayout SettingLayout = new javax.swing.GroupLayout(Setting);
        Setting.setLayout(SettingLayout);
        SettingLayout.setHorizontalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(se)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        SettingLayout.setVerticalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(se))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(new Color(55,55,55));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void robotsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotsMouseEntered
        robots.setBackground(new Color(20,20,20));
        ro.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_robotsMouseEntered

    private void robotsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotsMouseExited
        robots.setBackground(new Color(55,55,55));
        ro.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_robotsMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new GO_AI.Main_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void in1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in1MouseEntered
        in1.setBackground(new Color(20,20,20));
        instructor1.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_in1MouseEntered

    private void in1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in1MouseExited
        in1.setBackground(new Color(55,55,55));
        instructor1.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_in1MouseExited

    private void workspace1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspace1MouseEntered
        workspace1.setBackground(new Color(20,20,20));
        wo1.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_workspace1MouseEntered

    private void workspace1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspace1MouseExited
        workspace1.setBackground(new Color(55,55,55));
        wo1.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_workspace1MouseExited

    private void SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseEntered

    }//GEN-LAST:event_SettingMouseEntered

    private void SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseExited

    }//GEN-LAST:event_SettingMouseExited

    private void feedback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback1MouseClicked
        new GO_AI.Feedback_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_feedback1MouseClicked

    private void feedback1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback1MouseEntered
        feedback1.setBackground(new Color(20,20,20));
        fe1.setForeground(new Color(75,155,144));
    }//GEN-LAST:event_feedback1MouseEntered

    private void feedback1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback1MouseExited
        feedback1.setBackground(new Color(55,55,55));
        fe1.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_feedback1MouseExited

    private void Finish3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Finish3MouseClicked
        if(redColor.isSelected()){
        new GO_AI.Main().setVisible(true);
        dispose();
        }else{
        new GO_AI.Main_2().setVisible(true);
        dispose();    
        }
        
    }//GEN-LAST:event_Finish3MouseClicked

    private void in1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in1MouseClicked
        new GO_AI.Instructor_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_in1MouseClicked

    private void workspace1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspace1MouseClicked
        new GO_AI.Workspace_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_workspace1MouseClicked

    private void robotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotsMouseClicked
        new GO_AI.Robot_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_robotsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GO_AI.Setting_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Finish3;
    private javax.swing.JPanel Setting;
    private javax.swing.JLabel fe1;
    private javax.swing.JPanel feedback1;
    private javax.swing.JPanel in1;
    private javax.swing.JLabel instructor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox redColor;
    private javax.swing.JLabel ro;
    private javax.swing.JPanel robots;
    private javax.swing.JLabel se;
    private javax.swing.JLabel wo1;
    private javax.swing.JPanel workspace1;
    // End of variables declaration//GEN-END:variables
}
