/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalExam;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sheha
 */
public class All_control extends javax.swing.JFrame {

    /**
     * Creates new form All_control
     */
    public All_control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        save = new javax.swing.JButton();
        cut = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        power = new javax.swing.JButton();
        divid1 = new javax.swing.JButton();
        line = new javax.swing.JButton();
        X = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        u = new javax.swing.JTextArea();
        txtf = new javax.swing.JLabel();
        txtp = new javax.swing.JLabel();
        txts = new javax.swing.JLabel();
        txtl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setLayout(null);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 140, 410, 10);

        save.setText("Save To File");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(10, 150, 400, 23);

        cut.setText("Cut");
        cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutActionPerformed(evt);
            }
        });
        jPanel1.add(cut);
        cut.setBounds(10, 180, 400, 23);

        sqrt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sqrt.setText("File");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });
        jPanel1.add(sqrt);
        sqrt.setBounds(10, 220, 70, 23);

        power.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        power.setText("Parent");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });
        jPanel1.add(power);
        power.setBounds(10, 270, 70, 23);

        divid1.setText("Size");
        divid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divid1ActionPerformed(evt);
            }
        });
        jPanel1.add(divid1);
        divid1.setBounds(10, 320, 70, 23);

        line.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        line.setText("Lines");
        line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineActionPerformed(evt);
            }
        });
        jPanel1.add(line);
        line.setBounds(10, 370, 70, 23);

        X.setBackground(new java.awt.Color(0, 239, 221));
        X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        X.setForeground(new java.awt.Color(255, 0, 255));
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        X.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        jPanel1.add(X);
        X.setBounds(390, 10, 30, 30);

        h.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(h);
        h.setBounds(20, 280, 50, 30);

        u.setBackground(new java.awt.Color(1, 1, 1));
        u.setColumns(20);
        u.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        u.setForeground(new java.awt.Color(255, 255, 255));
        u.setRows(5);
        u.setText("This Paragraph\ncontains alot of lines\nin the source code,\nwe need to do something");
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(u);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 350, 100);

        txtf.setForeground(new java.awt.Color(255, 255, 255));
        txtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 135, 135), 1, true));
        jPanel1.add(txtf);
        txtf.setBounds(110, 224, 300, 20);

        txtp.setForeground(new java.awt.Color(255, 255, 255));
        txtp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 135, 135), 1, true));
        jPanel1.add(txtp);
        txtp.setBounds(110, 274, 300, 20);

        txts.setForeground(new java.awt.Color(255, 255, 255));
        txts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 135, 135), 1, true));
        jPanel1.add(txts);
        txts.setBounds(110, 320, 300, 20);

        txtl.setForeground(new java.awt.Color(255, 255, 255));
        txtl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 135, 135), 1, true));
        jPanel1.add(txtl);
        txtl.setBounds(110, 374, 300, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void lineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineActionPerformed
        
        FileReader     fr = null;
        BufferedReader br = null;
        int          line = 0;
        try {
            File   f      = new File("data.txt");
            fr            = new FileReader(f);
            br            = new BufferedReader(fr);
            String m      = null;
            while( (m=br.readLine()) != null){
                   line   = line+1;
            }
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally{
            try {
                br.close();
                fr.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
        }
        
        txtl.setText(""+line);
    }//GEN-LAST:event_lineActionPerformed

    private void divid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divid1ActionPerformed
        File            f = new File("data.txt");
        long size = f.length();
        txts.setText(size + "BYTE");
        System.out.println(f.getAbsoluteFile());
    }//GEN-LAST:event_divid1ActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
        File            f = new File("data.txt");
        txtp.setText(f.getParent());
    }//GEN-LAST:event_powerActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
        File            f = new File("data.txt");
        txtf.setText(f.getName());
    }//GEN-LAST:event_sqrtActionPerformed

    private void cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutActionPerformed
        File f  = new File("data.txt");
        File f2 = new File("C:\\Users\\sheha\\OneDrive\\Desktop\\data.txt");
        FileReader fr = null;
        FileWriter fw = null;
        BufferedReader br = null;
        BufferedWriter bw = null;
        try {
            fr = new FileReader(f);
            br = new BufferedReader(fr);
            fw = new FileWriter(f2);
            bw = new BufferedWriter(fw);
            String m = null;
            
            while((m = br.readLine())!= null){
                bw.write(m);
                bw.newLine();
            }
            f.delete();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());   
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally{
            try {
                JOptionPane.showMessageDialog(this, "Done Cut");
                
                br.close();
                fr.close();
                bw.close();
                fw.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_cutActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        File            f = new File("data.txt"); 
        FileWriter     fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(f);
            bw =  new BufferedWriter(fw);
            bw.write(u.getText());
            JOptionPane.showMessageDialog(this, " File Saved");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                bw.close();
                fw.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uMouseClicked
        if(u.getText().equals("This Paragraph contains alot of lines in the source code, we need to do something ")){
            u.setText("");
        }
    }//GEN-LAST:event_uMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.JButton cut;
    private javax.swing.JButton divid1;
    private javax.swing.JLabel h;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton line;
    private javax.swing.JButton power;
    private javax.swing.JButton save;
    private javax.swing.JButton sqrt;
    private javax.swing.JLabel txtf;
    private javax.swing.JLabel txtl;
    private javax.swing.JLabel txtp;
    private javax.swing.JLabel txts;
    private javax.swing.JTextArea u;
    // End of variables declaration//GEN-END:variables
}
