/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalExam;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JOptionPane;

/**
 *
 * @author sheha
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        u = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        BackSpace = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        power = new javax.swing.JButton();
        divid1 = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        divided = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        three = new javax.swing.JButton();
        two = new javax.swing.JButton();
        one = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        X = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        h = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setLayout(null);

        u.setBackground(new java.awt.Color(1, 1, 1));
        u.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        u.setForeground(new java.awt.Color(255, 255, 255));
        u.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(109, 109, 109), 1, true));
        jPanel1.add(u);
        u.setBounds(20, 50, 350, 50);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(20, 110, 350, 10);

        BackSpace.setText("BackSpace");
        BackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackSpaceActionPerformed(evt);
            }
        });
        jPanel1.add(BackSpace);
        BackSpace.setBounds(20, 120, 160, 23);

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(210, 120, 160, 23);

        sqrt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sqrt.setText("sqrt");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });
        jPanel1.add(sqrt);
        sqrt.setBounds(310, 160, 60, 23);

        power.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        power.setText("x^2");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });
        jPanel1.add(power);
        power.setBounds(310, 200, 60, 23);

        divid1.setText("1/x");
        divid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divid1ActionPerformed(evt);
            }
        });
        jPanel1.add(divid1);
        divid1.setBounds(310, 240, 60, 23);

        equal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel1.add(equal);
        equal.setBounds(310, 280, 60, 23);

        divided.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        divided.setText("/");
        divided.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividedActionPerformed(evt);
            }
        });
        jPanel1.add(divided);
        divided.setBounds(240, 160, 50, 23);

        mult.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mult.setText("*");
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });
        jPanel1.add(mult);
        mult.setBounds(240, 200, 50, 23);

        sub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub);
        sub.setBounds(240, 240, 50, 25);

        sum.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sum.setText("+");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        jPanel1.add(sum);
        sum.setBounds(240, 280, 50, 23);

        seven.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel1.add(seven);
        seven.setBounds(20, 160, 50, 23);

        eight.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel1.add(eight);
        eight.setBounds(90, 160, 50, 23);

        dot.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });
        jPanel1.add(dot);
        dot.setBounds(160, 280, 50, 21);

        nine.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel1.add(nine);
        nine.setBounds(160, 160, 50, 23);

        four.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel1.add(four);
        four.setBounds(20, 200, 50, 23);

        five.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel1.add(five);
        five.setBounds(90, 200, 50, 23);

        six.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel1.add(six);
        six.setBounds(160, 200, 50, 23);

        three.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel1.add(three);
        three.setBounds(160, 240, 50, 23);

        two.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel1.add(two);
        two.setBounds(90, 240, 50, 23);

        one.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel1.add(one);
        one.setBounds(20, 240, 50, 23);

        zero.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel1.add(zero);
        zero.setBounds(90, 280, 50, 23);

        X.setBackground(new java.awt.Color(0, 239, 221));
        X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        X.setForeground(new java.awt.Color(255, 0, 255));
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        X.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        jPanel1.add(X);
        X.setBounds(350, 10, 30, 30);

        txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt.setForeground(new java.awt.Color(135, 135, 135));
        txt.setText("Please Enter Your First Number");
        jPanel1.add(txt);
        txt.setBounds(20, 14, 190, 20);

        h.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(h);
        h.setBounds(20, 280, 50, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        u.setText(u.getText()+"0");
        
    }//GEN-LAST:event_zeroActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        u.setText(u.getText()+"1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        u.setText(u.getText()+"2");
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        u.setText(u.getText()+"3");
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        u.setText(u.getText()+"4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        u.setText(u.getText()+"5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        u.setText(u.getText()+"6");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        u.setText(u.getText()+"7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        u.setText(u.getText()+"8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        u.setText(u.getText()+"9");
    }//GEN-LAST:event_nineActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        u.setText(u.getText()+".");
    }//GEN-LAST:event_dotActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        u.setText("");
        h.setText("");
        txt.setText("Please Enter Your First Number");
    }//GEN-LAST:event_ClearActionPerformed

    private void BackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackSpaceActionPerformed
        String uu = u.getText();
        if (uu.isEmpty()== false){
            uu = uu.substring(0, uu.length() - 1 );
        }
        u.setText(uu);
    }//GEN-LAST:event_BackSpaceActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
    try{ 
           double uu = Double.parseDouble(u.getText());
           u.setText(""+Math.sqrt(uu) );
           txt.setText("Result is Below ");
    }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }           
    }//GEN-LAST:event_sqrtActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
    try{
           double uu = Double.parseDouble(u.getText());
           u.setText(""+ uu * uu);
           txt.setText("Result is Below ");
    }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_powerActionPerformed

    private void divid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divid1ActionPerformed
        try{
            double uu = Double.parseDouble(u.getText());
            u.setText(""+ 1/uu);
            txt.setText("Result is Below ");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_divid1ActionPerformed

    private void dividedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividedActionPerformed
    try{
            u.setText(u.getText()+"/");
    }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }    
    }//GEN-LAST:event_dividedActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
    try{
            u.setText(u.getText()+"*");
    }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }    
    }//GEN-LAST:event_multActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
    try{
            u.setText(u.getText()+"-");
    }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_subActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
    try{
            u.setText(u.getText()+"+");
    }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }    
    }//GEN-LAST:event_sumActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
    try{
          ScriptEngineManager mgr = new ScriptEngineManager();
          ScriptEngine engine     = mgr.getEngineByName("JavaScript");
          String       number     = u.getText();
          u.setText(""+ engine.eval(number));
    }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }   
    }//GEN-LAST:event_equalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackSpace;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel X;
    private javax.swing.JButton divid1;
    private javax.swing.JButton divided;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel h;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton mult;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton power;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton sub;
    private javax.swing.JButton sum;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField u;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
