/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalExam;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sheha
 */
public class Insert_With_Table extends javax.swing.JFrame {

    /**
     * Creates new form Insert_With_Table
     */
    public Insert_With_Table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        a = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        e = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setLayout(null);

        X.setBackground(new java.awt.Color(0, 239, 221));
        X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        X.setForeground(new java.awt.Color(255, 0, 255));
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        X.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        jPanel1.add(X);
        X.setBounds(770, 10, 30, 30);

        h.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(h);
        h.setBounds(20, 280, 50, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Students Age");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 230, 80, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Students id ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 80, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 80, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Students Phone");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 90, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Students Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 180, 90, 14);

        ADD.setText("ADD Student");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel1.add(ADD);
        ADD.setBounds(360, 290, 110, 23);

        t.setBackground(new java.awt.Color(1, 1, 1));
        t.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 135, 135), 3, true));
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "mohamed", "01001343385", "mohamed@gmail.com", "18"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, "", null, null, null}
            },
            new String [] {
                "Student Id", "Student Name", "Student Phone", "Student Email", "Student Age"
            }
        ));
        t.setGridColor(new java.awt.Color(255, 255, 255));
        t.setRowHeight(30);
        t.setRowMargin(2);
        t.setSelectionForeground(new java.awt.Color(1, 1, 1));
        jScrollPane1.setViewportView(t);
        t.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 70, 370, 150);

        a.setBackground(new java.awt.Color(1, 1, 1));
        a.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(a);
        a.setBounds(130, 230, 250, 30);

        i.setBackground(new java.awt.Color(1, 1, 1));
        i.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(i);
        i.setBounds(130, 30, 250, 30);

        n.setBackground(new java.awt.Color(1, 1, 1));
        n.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(n);
        n.setBounds(130, 80, 250, 30);

        p.setBackground(new java.awt.Color(1, 1, 1));
        p.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(p);
        p.setBounds(130, 130, 250, 30);

        e.setBackground(new java.awt.Color(1, 1, 1));
        e.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(e);
        e.setBounds(130, 180, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        int     id = Integer.parseInt(i.getText());
        String  nn = "'"+n.getText()+"'";
        String  pp = "'"+p.getText()+"'";
        String  ee = "'"+e.getText()+"'";
        int     aa = Integer.parseInt(a.getText());
        try {
            Connection c = connectionss.connect();
            Statement  s = c.createStatement();
            int        x = s.executeUpdate("insert into students values("+id+","+nn+","+pp+","+ee+","+aa+")");
            Object []  o = new Object[]{id,n.getText(),p.getText(),e.getText(),aa};
            if(x != 0){
                DefaultTableModel dtm = (DefaultTableModel) t.getModel();
                dtm.addRow(o);
            }else{
                JOptionPane.showMessageDialog(this, "INVALID DATA");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_ADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_With_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_With_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_With_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_With_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_With_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JLabel X;
    private javax.swing.JTextField a;
    private javax.swing.JTextField e;
    private javax.swing.JLabel h;
    private javax.swing.JTextField i;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField p;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
